// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupplierPortal.Server.Data.Context;

#nullable disable

namespace SupplierPortal.Server.Migrations
{
    [DbContext(typeof(SupplierDbContext))]
    [Migration("20230622091031_AddedSupplierTable")]
    partial class AddedSupplierTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupplierPortal.Shared.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("97a10af1-7f3f-4a07-8c40-40902f2a5a96"),
                            Company = "GetTechLimited",
                            Email = "gt@gt.com",
                            Name = "XYZ"
                        },
                        new
                        {
                            Id = new Guid("11c5e627-bcfa-4d99-a2e3-125e6b85fe30"),
                            Company = "Cleaning Limited",
                            Email = "clean@clean.com",
                            Name = "XYZ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
